primes2: primes2.c is_prime.s
	gcc -Wall primes2.c is_prime.s -o primes2

counte: counte.c counte.s
	gcc -Wall counte.c counte.s -o counte

matrix_sum: matrix_sum.c matrix_sum.s
	gcc -Wall matrix_sum.c matrix_sum.s -o matrix_sum

time: time.c time.s
	gcc -Wall time.c time.s -o time
