## Kartikeya Sharma
## CSCI 206 - 1 PM
## Lab 10 - Makefile
## Lab Date: 3/26/19

C=gcc
CFLAGS=-Wall

all: bits floats

bits: bits.c
	$(CC) $(CFLAGS) bits.c -o bits

floats: floats.c floats.s
	$(CC) $(CFLAGS) floats.c floats.s -o floats
